### ISSUE TITLE
Fix sample and docs

### ISSUE THREAD

**Issue by DirectXMan12** [openshift/service-idler#2]
Docs should be better, and sample is not filled out

**Comment by aditya-konarde** [comment]
I was trying to set this up on an OpenShift origin cluster, and definitely could use more descriptive docs. One scenario I am looking at, for example:

Given that I have a set of deployments across multiple projects, how do I set up the service idler to idle based on time, and also unidle them. What I need to get to is something similar to how the OpenShift Online idling works. 

Any documents/pointers are highly appreciated :)

**Comment by DirectXMan12** [comment]
The service-idler itself doesn't perform any automated idling -- it's intended as a building block for those purposes.  It deals with the nitty-gritty of idling and unidling, and capturing state, so that you can just deal with deciding what and when to idle.

So in your case, you'd construct the idler with the things you wanted to idle, and then you'd send a `patch` or `update` operation to set `wantIdle` to `true` to idle, or `false` to unidle.
